security:
    enable_authenticator_manager: true
    password_hashers:
        # Our user class and the algorithm we'll use to encode passwords
        # 'auto' means to let Symfony choose the best possible password hasher (Argon2 or Bcrypt)
        # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        auth_user_provider:
            id: App\Security\UserProvider
            
     
            
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        main:
            pattern: ^/
            remote_user:
                provider: auth_user_provider
            form_login:
                # "app_login" is the name of the route created previously
                login_path: app_login
                check_path: app_login
                username_parameter: email    
                password_parameter: passwd
            login_throttling:
                max_attempts: 3 
                interval: '5 minutes'
            logout:
                path: app_logout
                target: /
    access_control:
        - { path: '^/user/profile', roles: ROLE_USER }
        - { path: '^/parts', roles: ROLE_USER }
        - { path: '^/admin', roles: ROLE_ADMINISTRATOR }
